# Generated by Django 3.1.3 on 2021-01-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210106_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
