# Generated by Django 3.1.3 on 2021-01-15 00:28

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_address'),
        ('store', '0002_auto_20210112_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='afeez', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('SR', 'Sorting'), ('SH', 'Shipping'), ('DE', 'Delivered')], default='SR', max_length=2)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
