# Generated by Django 3.1.3 on 2021-01-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210117_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_line_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SR', 'Sorting'), ('SH', 'Shipping'), ('DE', 'Delivered')], max_length=2, null=True),
        ),
    ]
