# Generated by Django 3.1.3 on 2021-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
