# Generated by Django 3.1.3 on 2021-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('UK', 'United Kingdom')], default='NG', max_length=2),
        ),
    ]
