# Generated by Django 3.1.3 on 2021-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210118_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian naira'), ('GHS', 'Ghana'), ('KES', 'Kenya'), ('GBP', 'United Kingdom')], default='NGN', max_length=3),
        ),
    ]
