# Generated by Django 3.1.3 on 2021-01-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_store_dispatch_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_rider',
            field=models.BooleanField(default=False),
        ),
    ]
