# Generated by Django 3.1.3 on 2021-01-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_store_has_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
