# Generated by Django 3.1.3 on 2021-01-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210115_0028'),
        ('product', '0005_remove_order_customer'),
        ('checkout', '0002_auto_20210115_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
