# Generated by Django 3.1.3 on 2021-01-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_auto_20210117_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrider',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
