# Generated by Django 3.1.3 on 2021-01-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_auto_20210117_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchrider',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='dispatchrider',
            name='bank',
        ),
    ]
