# Generated by Django 3.1.3 on 2021-01-19 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0006_auto_20210119_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrider',
            name='has_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispatchrider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
