# Generated by Django 3.1.3 on 2021-01-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_signed'),
        ('dispatch', '0008_auto_20210119_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrider',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
