# Generated by Django 3.1.3 on 2021-01-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_shipping_fee'),
        ('checkout', '0002_auto_20210115_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.IntegerField()),
                ('shop_total', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('shipping_total', models.IntegerField()),
                ('rider_total', models.IntegerField()),
                ('shipping_commission', models.IntegerField()),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
    ]
