# Generated by Django 3.1.3 on 2021-01-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='rider_total',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='shipping_commission',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='shop_total',
        ),
    ]
