# Generated by Django 3.1.3 on 2021-01-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210117_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='amount_total',
            new_name='total',
        ),
    ]
