# Generated by Django 3.1.3 on 2021-01-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210117_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='total',
            new_name='cart_total',
        ),
    ]
